<<<<<<< HEAD
=======

>>>>>>> 39fb026 (Test push for new frontend environment setup.)
# This workflow will lint and build a React application created with create-react-app
# For more information see: https://create-react-app.dev/docs/running-tests/

name: React application

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test -- --watchAll=false

      - name: Run ESLint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build
